### PR TITLE
Blog app - creating a data model

### PR DESCRIPTION
**Pull request by codedit334**
## Hi Reviewer 👋,

In this PR:
- [x] Created a new app. It has a meaningful name.
- [x] Project has Postgres database set up.
- [x] Build my project schema.
  - Create and run the necessary migration files.
  - Table and column names should match the ERD diagram.
  - Photo for users table should be a link to an image
  - Foreign keys are included.
  - In posts table the column holding the foreign key to the users table are named author_id
  - All columns that are foreign keys  have a corresponding index.
 
# 🤝

### CODE REVIEW

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project meets all the requested requirements:heavy_check_mark: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by CollinsTatang — APPROVED** [review]
.

**Comment by codedit334** [comment]
Hi @CollinsTatang, Thank you for approving my work! Though, in my dashboard still shows review pending... Can you reapprove? Or suggest a solution :) Thanks in advance!

**Comment by codedit334** [comment]
@CollinsTatang Problem solved! Many thanks.

**Pull request merged**
